name: Vagrant Up

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
permissions:
  contents: read

jobs:
  # vagrant-up:
  #   runs-on: macos-13

  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: brew install virtualbox vagrant
      # Installing this is skipped in CI as using it was causing some corruption in
      # attempting to mount the shared folder. The guest and host guest additions
      # versions are close enough that we are fine without it.
      # - run: vagrant plugin install vagrant-vbguest
      # - run: NO_SUBMISSIONS=1 vagrant up ubuntu-22.04
      # - name: Validate image
      #   run: curl --show-error --fail --include http://localhost:1511
      # - name: Acquire Job ID
      #   if: failure()
      #   id: get-job-id
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
      #     job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
      #     echo "job_id=$job_id" >> $GITHUB_OUTPUT
      # - name: Send zulip message on failure
      #   if: failure()
      #   run: |
      #    curl -X POST https://submitty.zulipchat.com/api/v1/messages -u ${{ secrets.ZULIP_AUTHENTICATION }} --data-urlencode 'type=stream' --data-urlencode 'to=Submitty Developer Studio' --data-urlencode 'topic=Vagrant Up Failures' --data-urlencode 'content=The Vagrant Up Github Action has failed. View here: https://github.com/Submitty/Submitty/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}'

  vagrant-up-m1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get -y install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils vagrant qemu
          sudo systemctl enable --now libvirtd
          # sudo pwpolicy -u runner -sethashtypes SMB-NT on
          vagrant plugin install vagrant-libvirt

      # Installing this is skipped in CI as using it was causing some corruption in
      # attempting to mount the shared folder. The guest and host guest additions
      # versions are close enough that we are fine without it.
      # - run: vagrant plugin install vagrant-vbguest
      - run: |
          sudo su
          vagrant up --provider=libvirt
      - name: Validate image
        run: curl --show-error --fail --include http://localhost:1511
      # - name: Acquire Job ID
      #   if: failure()
      #   id: get-job-id
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
      #     job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
      #     echo "job_id=$job_id" >> $GITHUB_OUTPUT
      # - name: Send zulip message on failure
      #   if: failure()
      #   run: |
      #    curl -X POST https://submitty.zulipchat.com/api/v1/messages -u ${{ secrets.ZULIP_AUTHENTICATION }} --data-urlencode 'type=stream' --data-urlencode 'to=Submitty Developer Studio' --data-urlencode 'topic=Vagrant Up Failures' --data-urlencode 'content=The Vagrant Up Github Action has failed. View here: https://github.com/Submitty/Submitty/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}'
